package unbound

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"time"
)

var ErrInvalidSettings = errors.New("invalid unbound settings")

type Settings struct {
	QnameMinimisation bool `json:"qname_minimisation"`
	Prefetch          bool `json:"prefetch"`
	ServeExpired      bool `json:"serve_expired"`
	CacheMinTTL       int  `json:"cache_min_ttl"`
	CacheMaxTTL       int  `json:"cache_max_ttl"`
	Threads           int  `json:"threads"`
}

func DefaultSettings() Settings {
	return Settings{
		QnameMinimisation: true,
		Prefetch:          true,
		ServeExpired:      true,
		CacheMinTTL:       0,
		CacheMaxTTL:       86400,
		Threads:           2,
	}
}

func (s Settings) Validate() error {
	if s.CacheMinTTL < 0 || s.CacheMinTTL > 3600 {
		return fmt.Errorf("%w: cache_min_ttl must be between 0 and 3600", ErrInvalidSettings)
	}
	if s.CacheMaxTTL < 60 || s.CacheMaxTTL > 604800 {
		return fmt.Errorf("%w: cache_max_ttl must be between 60 and 604800", ErrInvalidSettings)
	}
	if s.CacheMinTTL > s.CacheMaxTTL {
		return fmt.Errorf("%w: cache_min_ttl must not exceed cache_max_ttl", ErrInvalidSettings)
	}
	if s.Threads < 1 || s.Threads > 32 {
		return fmt.Errorf("%w: threads must be between 1 and 32", ErrInvalidSettings)
	}
	return nil
}

func (s Settings) Render() ([]byte, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "# Generated by RootGuard. Do not edit manually.")
	fmt.Fprintln(&out, "server:")
	fmt.Fprintf(&out, "    qname-minimisation: %s\n", yesNo(s.QnameMinimisation))
	fmt.Fprintf(&out, "    prefetch: %s\n", yesNo(s.Prefetch))
	fmt.Fprintf(&out, "    serve-expired: %s\n", yesNo(s.ServeExpired))
	fmt.Fprintf(&out, "    cache-min-ttl: %d\n", s.CacheMinTTL)
	fmt.Fprintf(&out, "    cache-max-ttl: %d\n", s.CacheMaxTTL)
	fmt.Fprintf(&out, "    num-threads: %d\n", s.Threads)
	return out.Bytes(), nil
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

type Manager struct {
	hostConfigDir      string
	containerConfigDir string
	containerName      string
	run                commandRunner
	now                func() time.Time
	applyMu            sync.Mutex
}

type commandRunner func(context.Context, string, ...string) ([]byte, error)

func NewManager(hostConfigDir, containerConfigDir, containerName string) *Manager {
	return &Manager{
		hostConfigDir: hostConfigDir, containerConfigDir: containerConfigDir,
		containerName: containerName,
		run: func(ctx context.Context, name string, args ...string) ([]byte, error) {
			return exec.CommandContext(ctx, name, args...).CombinedOutput()
		},
		now: time.Now,
	}
}

func (m *Manager) Load() (Settings, error) {
	data, err := os.ReadFile(filepath.Join(m.hostConfigDir, "settings.json"))
	if errors.Is(err, os.ErrNotExist) {
		return DefaultSettings(), nil
	}
	if err != nil {
		return Settings{}, err
	}

	var settings Settings
	if err := json.Unmarshal(data, &settings); err != nil {
		return Settings{}, fmt.Errorf("decode saved settings: %w", err)
	}
	return settings, settings.Validate()
}

func (m *Manager) Apply(ctx context.Context, settings Settings) error {
	m.applyMu.Lock()
	defer m.applyMu.Unlock()

	config, err := settings.Render()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(m.hostConfigDir, 0755); err != nil {
		return fmt.Errorf("create config directory: %w", err)
	}

	tempConfig := filepath.Join(m.hostConfigDir, ".rootguard-unbound.conf.tmp")
	if err := os.WriteFile(tempConfig, config, 0644); err != nil {
		return fmt.Errorf("write temporary config: %w", err)
	}
	defer os.Remove(tempConfig)

	containerTemp := filepath.Join(m.containerConfigDir, filepath.Base(tempConfig))
	output, err := m.run(ctx, "docker", "exec", m.containerName, "unbound-checkconf", containerTemp)
	if err != nil {
		return fmt.Errorf("validate unbound config: %w: %s", err, output)
	}

	currentSettings, err := m.Load()
	if err != nil {
		return fmt.Errorf("load current settings: %w", err)
	}
	currentConfig, err := m.activeConfig(currentSettings)
	if err != nil {
		return err
	}
	if err := m.recordSnapshot(currentSettings, currentConfig); err != nil {
		return fmt.Errorf("record current unbound version: %w", err)
	}

	settingsData, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	settingsData = append(settingsData, '\n')
	configPath := filepath.Join(m.hostConfigDir, "50-rootguard.conf")
	settingsPath := filepath.Join(m.hostConfigDir, "settings.json")
	oldConfig, configExisted, err := readOptional(configPath)
	if err != nil {
		return fmt.Errorf("read previous unbound config: %w", err)
	}
	oldSettings, settingsExisted, err := readOptional(settingsPath)
	if err != nil {
		return fmt.Errorf("read previous unbound settings: %w", err)
	}

	if err := os.Rename(tempConfig, configPath); err != nil {
		return fmt.Errorf("activate unbound config: %w", err)
	}
	if err := writeAtomic(settingsPath, settingsData, 0600); err != nil {
		_ = restoreFile(configPath, oldConfig, configExisted, 0644)
		return fmt.Errorf("activate settings: %w", err)
	}

	output, err = m.run(ctx, "docker", "restart", m.containerName)
	if err != nil {
		rollbackErr := errors.Join(
			restoreFile(configPath, oldConfig, configExisted, 0644),
			restoreFile(settingsPath, oldSettings, settingsExisted, 0600),
		)
		rollbackOutput, restartErr := m.run(ctx, "docker", "restart", m.containerName)
		if rollbackErr != nil || restartErr != nil {
			return fmt.Errorf("restart unbound: %w: %s; rollback failed: %v; rollback restart: %v: %s", err, output, rollbackErr, restartErr, rollbackOutput)
		}
		return fmt.Errorf("restart unbound: %w: %s; previous configuration restored", err, output)
	}
	if err := m.recordSnapshot(settings, config); err != nil {
		return fmt.Errorf("record active unbound version: %w", err)
	}
	return nil
}

func (m *Manager) activeConfig(settings Settings) ([]byte, error) {
	data, err := os.ReadFile(filepath.Join(m.hostConfigDir, "50-rootguard.conf"))
	if errors.Is(err, os.ErrNotExist) {
		return settings.Render()
	}
	if err != nil {
		return nil, fmt.Errorf("read active unbound config: %w", err)
	}
	return data, nil
}

func writeAtomic(path string, data []byte, mode os.FileMode) error {
	temporary := path + ".tmp"
	if err := os.WriteFile(temporary, data, mode); err != nil {
		return err
	}
	if err := os.Rename(temporary, path); err != nil {
		_ = os.Remove(temporary)
		return err
	}
	return nil
}

func readOptional(path string) ([]byte, bool, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	return data, true, nil
}

func restoreFile(path string, data []byte, existed bool, mode os.FileMode) error {
	if !existed {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}
	return writeAtomic(path, data, mode)
}
