package unbound

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

var ErrInvalidSettings = errors.New("invalid unbound settings")

type Settings struct {
	QnameMinimisation bool `json:"qname_minimisation"`
	Prefetch          bool `json:"prefetch"`
	ServeExpired      bool `json:"serve_expired"`
	CacheMinTTL       int  `json:"cache_min_ttl"`
	CacheMaxTTL       int  `json:"cache_max_ttl"`
	Threads           int  `json:"threads"`
}

func DefaultSettings() Settings {
	return Settings{
		QnameMinimisation: true,
		Prefetch:          true,
		ServeExpired:      true,
		CacheMinTTL:       0,
		CacheMaxTTL:       86400,
		Threads:           2,
	}
}

func (s Settings) Validate() error {
	if s.CacheMinTTL < 0 || s.CacheMinTTL > 3600 {
		return fmt.Errorf("%w: cache_min_ttl must be between 0 and 3600", ErrInvalidSettings)
	}
	if s.CacheMaxTTL < 60 || s.CacheMaxTTL > 604800 {
		return fmt.Errorf("%w: cache_max_ttl must be between 60 and 604800", ErrInvalidSettings)
	}
	if s.CacheMinTTL > s.CacheMaxTTL {
		return fmt.Errorf("%w: cache_min_ttl must not exceed cache_max_ttl", ErrInvalidSettings)
	}
	if s.Threads < 1 || s.Threads > 32 {
		return fmt.Errorf("%w: threads must be between 1 and 32", ErrInvalidSettings)
	}
	return nil
}

func (s Settings) Render() ([]byte, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "# Generated by RootGuard. Do not edit manually.")
	fmt.Fprintln(&out, "server:")
	fmt.Fprintf(&out, "    qname-minimisation: %s\n", yesNo(s.QnameMinimisation))
	fmt.Fprintf(&out, "    prefetch: %s\n", yesNo(s.Prefetch))
	fmt.Fprintf(&out, "    serve-expired: %s\n", yesNo(s.ServeExpired))
	fmt.Fprintf(&out, "    cache-min-ttl: %d\n", s.CacheMinTTL)
	fmt.Fprintf(&out, "    cache-max-ttl: %d\n", s.CacheMaxTTL)
	fmt.Fprintf(&out, "    num-threads: %d\n", s.Threads)
	return out.Bytes(), nil
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

type Manager struct {
	hostConfigDir      string
	containerConfigDir string
	containerName      string
}

func NewManager(hostConfigDir, containerConfigDir, containerName string) *Manager {
	return &Manager{
		hostConfigDir: hostConfigDir, containerConfigDir: containerConfigDir,
		containerName: containerName,
	}
}

func (m *Manager) Load() (Settings, error) {
	data, err := os.ReadFile(filepath.Join(m.hostConfigDir, "settings.json"))
	if errors.Is(err, os.ErrNotExist) {
		return DefaultSettings(), nil
	}
	if err != nil {
		return Settings{}, err
	}

	var settings Settings
	if err := json.Unmarshal(data, &settings); err != nil {
		return Settings{}, fmt.Errorf("decode saved settings: %w", err)
	}
	return settings, settings.Validate()
}

func (m *Manager) Apply(ctx context.Context, settings Settings) error {
	config, err := settings.Render()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(m.hostConfigDir, 0755); err != nil {
		return fmt.Errorf("create config directory: %w", err)
	}

	tempConfig := filepath.Join(m.hostConfigDir, ".rootguard-unbound.conf.tmp")
	if err := os.WriteFile(tempConfig, config, 0644); err != nil {
		return fmt.Errorf("write temporary config: %w", err)
	}
	defer os.Remove(tempConfig)

	containerTemp := filepath.Join(m.containerConfigDir, filepath.Base(tempConfig))
	output, err := exec.CommandContext(
		ctx, "docker", "exec", m.containerName,
		"unbound-checkconf", containerTemp,
	).CombinedOutput()
	if err != nil {
		return fmt.Errorf("validate unbound config: %w: %s", err, output)
	}

	if err := os.Rename(tempConfig, filepath.Join(m.hostConfigDir, "50-rootguard.conf")); err != nil {
		return fmt.Errorf("activate unbound config: %w", err)
	}

	settingsData, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	settingsData = append(settingsData, '\n')
	settingsTemp := filepath.Join(m.hostConfigDir, ".settings.json.tmp")
	if err := os.WriteFile(settingsTemp, settingsData, 0600); err != nil {
		return fmt.Errorf("write settings: %w", err)
	}
	if err := os.Rename(settingsTemp, filepath.Join(m.hostConfigDir, "settings.json")); err != nil {
		return fmt.Errorf("activate settings: %w", err)
	}

	output, err = exec.CommandContext(ctx, "docker", "restart", m.containerName).CombinedOutput()
	if err != nil {
		return fmt.Errorf("restart unbound: %w: %s", err, output)
	}
	return nil
}
