package unbound

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

var ErrInvalidSettings = errors.New("invalid unbound settings")

type Settings struct {
	QnameMinimisation bool `json:"qname_minimisation"`
	Prefetch          bool `json:"prefetch"`
	ServeExpired      bool `json:"serve_expired"`
	CacheMinTTL       int  `json:"cache_min_ttl"`
	CacheMaxTTL       int  `json:"cache_max_ttl"`
	Threads           int  `json:"threads"`
}

type ActiveConfiguration struct {
	BaseConfig    string    `json:"base_config"`
	ManagedConfig string    `json:"managed_config"`
	CustomConfig  string    `json:"custom_config"`
	CheckedAt     time.Time `json:"checked_at"`
}

func DefaultSettings() Settings {
	return Settings{
		QnameMinimisation: true,
		Prefetch:          true,
		ServeExpired:      true,
		CacheMinTTL:       0,
		CacheMaxTTL:       86400,
		Threads:           2,
	}
}

func (s Settings) Validate() error {
	if s.CacheMinTTL < 0 || s.CacheMinTTL > 3600 {
		return fmt.Errorf("%w: cache_min_ttl must be between 0 and 3600", ErrInvalidSettings)
	}
	if s.CacheMaxTTL < 60 || s.CacheMaxTTL > 604800 {
		return fmt.Errorf("%w: cache_max_ttl must be between 60 and 604800", ErrInvalidSettings)
	}
	if s.CacheMinTTL > s.CacheMaxTTL {
		return fmt.Errorf("%w: cache_min_ttl must not exceed cache_max_ttl", ErrInvalidSettings)
	}
	if s.Threads < 1 || s.Threads > 32 {
		return fmt.Errorf("%w: threads must be between 1 and 32", ErrInvalidSettings)
	}
	return nil
}

func (s Settings) Render() ([]byte, error) {
	if err := s.Validate(); err != nil {
		return nil, err
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "# Generated by RootGuard. Do not edit manually.")
	fmt.Fprintln(&out, "server:")
	fmt.Fprintln(&out, "    # Privacy: reveal only the currently required DNS label to each authoritative server.")
	fmt.Fprintf(&out, "    qname-minimisation: %s\n", yesNo(s.QnameMinimisation))
	fmt.Fprintln(&out, "    # Performance: refresh frequently used records shortly before their TTL expires.")
	fmt.Fprintf(&out, "    prefetch: %s\n", yesNo(s.Prefetch))
	fmt.Fprintln(&out, "    # Availability: keep serving cached records during temporary upstream failures.")
	fmt.Fprintf(&out, "    serve-expired: %s\n", yesNo(s.ServeExpired))
	fmt.Fprintln(&out, "    # Cache floor in seconds; higher values delay authoritative DNS changes.")
	fmt.Fprintf(&out, "    cache-min-ttl: %d\n", s.CacheMinTTL)
	fmt.Fprintln(&out, "    # Cache ceiling in seconds; records are never retained longer than this value.")
	fmt.Fprintf(&out, "    cache-max-ttl: %d\n", s.CacheMaxTTL)
	fmt.Fprintln(&out, "    # Parallel resolver workers; match this to the available CPU resources.")
	fmt.Fprintf(&out, "    num-threads: %d\n", s.Threads)
	return out.Bytes(), nil
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}

type Manager struct {
	hostConfigDir      string
	containerConfigDir string
	containerName      string
	run                commandRunner
	now                func() time.Time
	applyMu            sync.Mutex
}

type commandRunner func(context.Context, string, ...string) ([]byte, error)

func NewManager(hostConfigDir, containerConfigDir, containerName string) *Manager {
	return &Manager{
		hostConfigDir: hostConfigDir, containerConfigDir: containerConfigDir,
		containerName: containerName,
		run: func(ctx context.Context, name string, args ...string) ([]byte, error) {
			return exec.CommandContext(ctx, name, args...).CombinedOutput()
		},
		now: time.Now,
	}
}

func (m *Manager) Load() (Settings, error) {
	data, err := os.ReadFile(filepath.Join(m.hostConfigDir, "settings.json"))
	if errors.Is(err, os.ErrNotExist) {
		return DefaultSettings(), nil
	}
	if err != nil {
		return Settings{}, err
	}

	var settings Settings
	if err := json.Unmarshal(data, &settings); err != nil {
		return Settings{}, fmt.Errorf("decode saved settings: %w", err)
	}
	return settings, settings.Validate()
}

func (m *Manager) ActiveConfiguration(ctx context.Context) (ActiveConfiguration, error) {
	readContainerFile := func(path string) (string, error) {
		output, err := m.run(ctx, "docker", "exec", m.containerName, "cat", path)
		if err != nil {
			return "", fmt.Errorf("read active Unbound file %s: %w: %s", path, err, strings.TrimSpace(string(output)))
		}
		return string(output), nil
	}

	base, err := readContainerFile("/etc/unbound/unbound.conf")
	if err != nil {
		return ActiveConfiguration{}, err
	}
	managed, err := readContainerFile("/etc/unbound/unbound.d/50-rootguard.conf")
	if err != nil {
		return ActiveConfiguration{}, err
	}
	custom, err := m.LoadCustom()
	if err != nil {
		return ActiveConfiguration{}, err
	}
	return ActiveConfiguration{
		BaseConfig:    base,
		ManagedConfig: managed,
		CustomConfig:  custom.Content,
		CheckedAt:     m.now().UTC(),
	}, nil
}

func (m *Manager) Apply(ctx context.Context, settings Settings) error {
	m.applyMu.Lock()
	defer m.applyMu.Unlock()
	custom, err := m.LoadCustom()
	if err != nil {
		return err
	}
	return m.applyStateLocked(ctx, settings, custom.Content)
}

func (m *Manager) applyStateLocked(ctx context.Context, settings Settings, custom string) error {
	config, err := settings.Render()
	if err != nil {
		return err
	}
	custom, err = normalizeCustom(custom)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(m.hostConfigDir, 0755); err != nil {
		return fmt.Errorf("create config directory: %w", err)
	}
	if _, err := m.validateCombined(ctx, settings, custom); err != nil {
		return err
	}

	currentSettings, err := m.Load()
	if err != nil {
		return fmt.Errorf("load current settings: %w", err)
	}
	currentConfig, err := m.activeConfig(currentSettings)
	if err != nil {
		return err
	}
	currentCustom, err := m.LoadCustom()
	if err != nil {
		return err
	}
	if err := m.recordSnapshot(currentSettings, currentConfig, []byte(currentCustom.Content)); err != nil {
		return fmt.Errorf("record current unbound version: %w", err)
	}

	settingsData, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return err
	}
	settingsData = append(settingsData, '\n')
	configPath := filepath.Join(m.hostConfigDir, "50-rootguard.conf")
	customPath := filepath.Join(m.hostConfigDir, "90-rootguard-custom.conf")
	settingsPath := filepath.Join(m.hostConfigDir, "settings.json")
	oldConfig, configExisted, err := readOptional(configPath)
	if err != nil {
		return fmt.Errorf("read previous unbound config: %w", err)
	}
	oldSettings, settingsExisted, err := readOptional(settingsPath)
	if err != nil {
		return fmt.Errorf("read previous unbound settings: %w", err)
	}
	oldCustom, customExisted, err := readOptional(customPath)
	if err != nil {
		return fmt.Errorf("read previous custom unbound config: %w", err)
	}

	if err := writeAtomic(configPath, config, 0644); err != nil {
		return fmt.Errorf("activate unbound config: %w", err)
	}
	if err := writeAtomic(settingsPath, settingsData, 0600); err != nil {
		_ = restoreFile(configPath, oldConfig, configExisted, 0644)
		return fmt.Errorf("activate settings: %w", err)
	}
	if err := writeOrRemove(customPath, []byte(custom), 0644); err != nil {
		_ = restoreFile(configPath, oldConfig, configExisted, 0644)
		_ = restoreFile(settingsPath, oldSettings, settingsExisted, 0600)
		return fmt.Errorf("activate custom config: %w", err)
	}

	output, err := m.run(ctx, "docker", "exec", m.containerName, "unbound-checkconf", "/etc/unbound/unbound.conf")
	if err != nil {
		rollbackErr := restoreState(configPath, settingsPath, customPath, oldConfig, oldSettings, oldCustom, configExisted, settingsExisted, customExisted)
		return fmt.Errorf("validate effective unbound config: %w: %s; files restored: %v", err, output, rollbackErr)
	}

	output, err = m.run(ctx, "docker", "restart", m.containerName)
	if err != nil {
		rollbackErr := restoreState(configPath, settingsPath, customPath, oldConfig, oldSettings, oldCustom, configExisted, settingsExisted, customExisted)
		rollbackOutput, restartErr := m.run(ctx, "docker", "restart", m.containerName)
		if rollbackErr != nil || restartErr != nil {
			return fmt.Errorf("restart unbound: %w: %s; rollback failed: %v; rollback restart: %v: %s", err, output, rollbackErr, restartErr, rollbackOutput)
		}
		return fmt.Errorf("restart unbound: %w: %s; previous configuration restored", err, output)
	}
	if err := m.recordSnapshot(settings, config, []byte(custom)); err != nil {
		return fmt.Errorf("record active unbound version: %w", err)
	}
	return nil
}

func writeOrRemove(path string, data []byte, mode os.FileMode) error {
	if len(data) == 0 {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}
	return writeAtomic(path, data, mode)
}

func restoreState(configPath, settingsPath, customPath string, config, settings, custom []byte, configExisted, settingsExisted, customExisted bool) error {
	return errors.Join(
		restoreFile(configPath, config, configExisted, 0644),
		restoreFile(settingsPath, settings, settingsExisted, 0600),
		restoreFile(customPath, custom, customExisted, 0644),
	)
}

func (m *Manager) activeConfig(settings Settings) ([]byte, error) {
	data, err := os.ReadFile(filepath.Join(m.hostConfigDir, "50-rootguard.conf"))
	if errors.Is(err, os.ErrNotExist) {
		return settings.Render()
	}
	if err != nil {
		return nil, fmt.Errorf("read active unbound config: %w", err)
	}
	return data, nil
}

func writeAtomic(path string, data []byte, mode os.FileMode) error {
	temporary := path + ".tmp"
	if err := os.WriteFile(temporary, data, mode); err != nil {
		return err
	}
	if err := os.Rename(temporary, path); err != nil {
		_ = os.Remove(temporary)
		return err
	}
	return nil
}

func readOptional(path string) ([]byte, bool, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, err
	}
	return data, true, nil
}

func restoreFile(path string, data []byte, existed bool, mode os.FileMode) error {
	if !existed {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}
	return writeAtomic(path, data, mode)
}
